service: smart-weight-tracker

provider:
  name: aws
  profile: avi92avi
  runtime: python3.7
  region: us-east-1
  project: smart-weight-tracker
  memorySize: 256
  timeout: 300
 
package:
  exclude:
    - node_modules/**
    - .gitignore 
    - __pycache__/**
    - tests/**
    - package.json
    - package-lock.json

functions:
  mainFn:
    handler: main.handler
    events:
      - http:
          path: /
          method: post
          cors: true # @cors_headers() from lambda_decorators package also used on functions
          # Content-Type: application/json

plugins:
  - serverless-python-requirements
  - serverless-domain-manager


custom:
  pythonRequirements:
    pythonBin: "/usr/bin/python3"
  customDomain:
    domainName: 'swtapi.aws.apoorv.sh'
    # stage: ci
    basePath: ''
    createRoute53Record: true
    certificateName: '*.aws.apoorv.sh'  
    # endpointType: 'regional'
    # securityPolicy: tls_1_2
    # apiType: rest