service: smart-weight-tracker

provider:
  name: aws
  profile: avi92avi
  runtime: python3.7
  region: ap-south-1
  project: smart-weight-tracker
  memorySize: 256
  timeout: 30
  environment:
    MONGODB_USER: ${ssm:MONGODB_USER}	
    MONGODB_PASSWORD: ${ssm:MONGODB_PASSWORD}	
 
package:
  exclude:
    - node_modules/**
    - .gitignore 
    - __pycache__/**
    - tests/**
    - package.json
    - package-lock.json

functions:
  mainFn:
    handler: main.handler
    events:
      - http:
          path: /
          method: post
          cors: true
          private: true

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

resources:
  Resources:
    MyServiceUsagePlan:
      Type: "AWS::ApiGateway::UsagePlan"
      DependsOn: ApiGatewayRestApi
      Properties:
        UsagePlanName: swt-usagePlan
        ApiStages:
          - ApiId:
              Ref: ApiGatewayRestApi
            Stage: dev
    
    MyServiceUsagePlanKey:
      Type: "AWS::ApiGateway::UsagePlanKey"
      DependsOn: MyServiceUsagePlan
      Properties :
        KeyId: ${ssm:SWT_API_KEY}	      
        KeyType: API_KEY
        UsagePlanId:
          Ref: MyServiceUsagePlan

custom:
  pythonRequirements:
    pythonBin: "/usr/bin/python3"
  customDomain:
    domainName: 'swtapi.aws.apoorv.sh'
    # stage: ci
    basePath: ''
    createRoute53Record: true
    certificateName: '*.aws.apoorv.sh'  
    # endpointType: 'regional'
    # securityPolicy: tls_1_2
    # apiType: rest
    