service: smart-weight-tracker

provider:
  name: google
  profile: avi92avi
  runtime: python37
  region: us-east-1
  project: smart-weight-tracker
  # memorySize: 256
  # timeout: 300
 
package:
  exclude:
    - node_modules/**
    - .gitignore 
    - __pycache__/**
    - tests/**
    - package.json
    - package-lock.json

functions:
  mainFn:
    handler: main.handler
    events:
      - http:
        method: post
        cors: true # @cors_headers() from lambda_decorators package also used on functions
        Content-Type: application/json

plugins:
  - serverless-python-requirements
  - serverless-domain-manager


custom:
  pythonRequirements:
    pythonBin: "/usr/bin/python3"
  customDomain:
    domainName: swt.apoorv.sh
    # stage: ci
    # basePath: api
    certificateName: '*.apoorv.sh'
    createRoute53Record: true
    # endpointType: 'regional'
    # securityPolicy: tls_1_2
    # apiType: rest